# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d592ce337f565f36f6f06b6b71ff696fde760fe17d44ddb992cf1b073ff1c092b509ae6236d8c765737c75d65ed52924327749f9550a92b7428e622c4edfff08

test:
  secret_key_base: 8589440b9a1f5326e9142a296841ae5ba66b4b14fcbd2ded87f917e1238140834d514593f9acd286571aea04e8b95cdeab3c9e776c7b31a6327c0ca7c780f4c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
